services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: is24ecc-backend
    container_name: is24ecc-node-backend
    command: /usr/src/app/node_modules/.bin/nodemon app.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: is24ecc-frontend
    container_name: is24ecc-react-frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  web-root:
    driver: local
